%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 29-Sep-2018 18:12:58
set(0,'defaultTextInterpreter','latex');
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(lampa.D,lampa.U,'MarkerSize',10,'Marker','o','LineStyle','none','Color',[0 0 0]);

% Create plot
plot(lampa1.D,lampa1.U,'MarkerSize',10,'Marker','x','LineStyle','none','Color',[0 0 0]);

% Create xlabel
xlabel({'$\sigma,deg$'},'FontSize',24,'Interpreter','latex');

% Create ylabel
ylabel({'U, c.u.'},'FontSize',24,'Interpreter','latex');

box(axes1,'on');
% Create arrow
annotation(figure1,'arrow',[0.445386064030129 0.414312617702448],...
    [0.783382284382284 0.756410256410256]);

% Create arrow
annotation(figure1,'arrow',[0.59322033898305 0.630885122410546],...
    [0.884615384615385 0.8997668997669]);

% Create line
annotation(figure1,'line',[0.645456365354105 0.645874226933165],...
    [0.123691556076053 0.861335315774568],'LineStyle',':');

% Create arrow
annotation(figure1,'arrow',[0.630794089701354 0.630794089701355],...
    [0.480387382088316 0.522179922880857]);

% Create arrow
annotation(figure1,'arrow',[0.175141242937852 0.13935969868173],...
    [0.143356643356643 0.144522144522145]);

% Create arrow
annotation(figure1,'arrow',[0.193032015065911 0.193032015065911],...
    [0.352146853146853 0.307692307692308]);

% Create textbox
annotation(figure1,'textbox',...
    [0.186499058380412 0.132867132867133 0.0818625235404916 0.0384615384615386],...
    'String',{'$\sigma''=41$'},...
    'Interpreter','latex',...
    'FontSize',18,...
    'FitBoxToText','off');

% Create line
annotation(figure1,'line',[0.180532665515718 0.179024356939252],...
    [0.484515878018934 0.13047894473128],'LineStyle',':');

% Create textbox
annotation(figure1,'textbox',...
    [0.650717514124293 0.129370629370629 0.0884538606403021 0.0361305361305361],...
    'String','$\sigma''''=50$',...
    'Interpreter','latex',...
    'FontSize',18,...
    'FitBoxToText','off');

% pos = get(h,'Position');
% set(h,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
% print(h,'graph\graph1','-dpdf','-r0')

% plot(lampa1.D,lampa1.U,'x')


% figure()
% plot(lampa2.D,lampa2.U,'*')
% hold on
% plot(lampa3.D,lampa3.U,'*')